### ISSUE TITLE
Apps v2: Release command should attempt PRIMARY_REGION env var

### ISSUE THREAD

**Issue by mrkurt** [superfly/flyctl#1608] opened 2023-01-21 02:43 UTC
Apps that talk to databases need their release commands run in the same region as their DB. We hacked in support for this by making release commands look for a `PRIMARY_REGION` environment variable, and attempt to run there it if exists.

**Comment by jsierles** [comment] 2023-01-24 15:47
In the first attempt at v2 fly.toml, we added a top-level `primary_region` which would set an env var. Do we want to keep this or stick with environment variables?

**Comment by alichay** [comment] 2023-02-20 20:57
As an update, this seems to be currently handled.

[Currently, the environment variable set in `fly.toml` overrides `primary_region` if the environment variable is set.](https://github.com/superfly/flyctl/blob/46cac31460c7e9a20693b65ae26f432b777a7a79/internal/command/deploy/deploy.go#L157-L159)

Is there anything else to discuss, or can this be closed?

**Comment by billyb2** [comment] 2023-03-06 15:20
Should this be closed?

**Comment by gwuah** [comment] 2023-03-09 21:20
Closing this because I can confirm we're passing the primary_region set in app_config to the launchInput for the release machine. https://github.com/superfly/flyctl/blob/e37a0222f08106f626e3482ed3de43d81a5b8e32/internal/command/deploy/machines.go#L359

**Closed by gwuah** 2023-03-09 21:20 UTC
Labels: bug
