### ISSUE TITLE
flyctl ssh console - missing terminal functionality on Windows; arrow keys, forward-delete, home/end etc.

### ISSUE THREAD

**Issue by kingIZZZY** [superfly/flyctl#1458] opened 2022-11-15 17:00 UTC
`flyctl ssh console`
Cannot scroll up/down through command history with arrow keys ⬆⬇
Cannot move cursor with ⬅➡ keys or skip words Ctrl+⬅ or Ctrl+➡ to edit line 
Cannot skip to beginning/end of line with Home / End
Seems there are fundamental Terminal functionalities missing - such as would be available with `docker exec -it`

* Windows 10
* `flyctl.exe v0.0.431 windows/amd64 Commit: eeef66af BuildDate: 2022-11-13T17:15:29Z`
* Dockerfile-based PHP project https://github.com/hyperf/hyperf-skeleton
  * Alpine linux `FROM hyperf/hyperf:8.1-alpine-v3.16-swoole`
  * by default it logs into `sh` - even then it should have these basic terminal line editing features
  * tried switching to `bash` - does not help, still can't line edit on the prompt line

**Comment by ndarilek** [comment] 2022-11-29 17:40
> tried switching to bash - does not help, still can't line edit on the prompt line

Do you mean switched to running bash in the SSH console? I'm wondering if this might be related to other possibly shell-related issues with `flyctl ssh console`. If you did run bash in the console and it still didn't help, then it may not be.

Also, what environment are you running flyctl in under Windows? Terminal, cmd, powershell, etc.? That unfortunately makes a huge difference, though it sounds like you're used to having that functionality and don't here so that may not be the issue.

Thanks.

**Comment by kingIZZZY** [comment] 2022-11-29 18:41
> * Windows 10

**Comment by ndarilek** [comment] 2022-11-29 18:44
Sorry, I meant were you running flyctl in the Windows Terminal app, the powershell CLI, cmd, or something else? Each of those handles the cursor a bit differently.

I'll probably be working on this at some point and I'd like to be sure I can replicate it first.

Thanks!

**Comment by kingIZZZY** [comment] 2022-11-29 19:15
[community.fly.io forum post](https://community.fly.io/t/flyctl-ssh-console-no-up-arrow-no-back-arrow-no-forward-delete-home-end-etc/8684)

I tried in all of the above, CMD, powershell, windows terminal, same behavior. When I try from Docker Desktop terminal for example it does seem to behave normally (i ssh into the local docker which runs on WSL2, then from there I install flyctl and run fly commands - then the terminal does behave correctly)

**Comment by ndarilek** [comment] 2022-11-29 19:26
Awesome, thanks for the additional context.

**Comment by hrumhurum** [comment] 2023-03-15 15:02
Console became broken again in one of the recent `flyctl` updates. The virtual terminal does not work anymore in the current version:

`flyctl.exe v0.0.488 windows/amd64 Commit: d56b165d BuildDate: 2023-03-15T14:36:24Z`

**Comment by ndarilek** [comment] 2023-03-15 15:35
Ugh, sorry to hear this. I'll do a bisect today and see if I can track 
down the cause.

**Comment by ndarilek** [comment] 2023-03-15 17:18
I'm not able to duplicate this. Do you have any specific steps I can use to replicate it?

Note that I believe SSH spins up /bin/sh by default. It's been a while since Linux was my daily driver, and I don't recall whether /bin/sh handles arrows. If I run `fly ssh console -a <myapp>`, type `ls` and then up arrow, I do indeed see arrow escape sequences. If OTOH I run /bin/bash, command history works fine.

**Comment by hrumhurum** [comment] 2023-03-15 21:38
The easiest way to reproduce it is to try using an interactive terminal application such as Midnight Commander.

> sudo apt-get install mc

Midnight Commander app is launched whenever you execute `mc` command in the shell. Under normal conditions, the app is responsive to arrow keys and renders itself as it should with correct boxed panels and stuff. Without the virtual terminal supports, Midnight Commander renders like junk, the screen is garbled and the app is not responsive to the arrow keys at all.

**Comment by ndarilek** [comment] 2023-03-16 17:57
Ah, I have to admit that I've never tested Windows terminal support quite to that extent since those types of interfaces are surprisingly inaccessible despite being all text. :)

Was there *ever* a point at which this worked? If so, and if it's an easy bisect, I'd say it's worth fixing. I know personally how it sucks not to be able to access tools like mc/top.

If it ever did work, do you know which version? Even if it wasn't necessarily the last version that worked, that'd be a helpful starting point.

Thanks.

**Comment by hrumhurum** [comment] 2023-03-16 23:20
> Was there _ever_ a point at which this worked?

Yes, the very first official `flyctl` releases with enabled virtual terminal support worked just fine. Unfortunately, I have not written down the exact version numbers, but they were from January 2023 as far as I remember.

**Comment by ndarilek** [comment] 2023-03-21 18:37
Not sure I'm going to be able to fix this one. I'm a blind screen reader user, and console-oriented UIs like mc/top are notoriously inaccessible.

In particular, I'm able to duplicate this behavior under mc, but 245a6395b71f7e3a45f66995cb8ce66050609588 which *should* correspond to the fix *also* duplicates the behavior for me. I'll try to brainstorm a fix, but just to check a few things:

1. Does launching the command in a bash shell make a difference?
2. Does up-arrowing through command history still work in bash?
3. Likewise, does left-arrow/right-arrow/delete work in bash?

Thanks.

**Comment by hrumhurum** [comment] 2023-05-15 15:34
The issue still persists in flyctl 0.1.4.

Here are some observations your were curious about:

> Does` launching the command in a bash shell make a difference?

No, launching `mc` in bash does not make a difference.

> Does up-arrowing through command history still work in bash?

Yes, it does.

> Likewise, does left-arrow/right-arrow/delete work in bash?

Yes, it does.

So, the virtual terminal support seems to work in general but not for all scenarios, as more complex apps like `mc` still fail. Personally, I have no idea where the problem may be, but when `flyctl ssh console` is used from Linux everything works fine. So it boils down to the virtual terminal support provided by Windows, encodings, or the way those things are initialized by `flyctl`.

**Comment by hrumhurum** [comment] 2023-05-15 15:57
My further experimentation signify that the issue might be caused by a non-flushed buffered data.

The following experiment demonstrates something weird:

1. `flyctl ssh console`
2. `bash`
3. `mcedit`. At this stage screen is filled with an incomplete screen of the editor. `mcedit` tool is a part of `mc` Midnight Commander software package
4. Press `F10`. This causes `mcedit` app to exit
5. Now, when you repeatedly press `Enter` in `bash`, you may start seeing gibberish symbols that are spit out after every key press. Those symbols resemble the parts of the app output, but the problem is that `mcedit` app has exited already. We should not see its output at this point, but we do

While that experiment is somewhat tricky to reproduce, it leads me to believe that `flyctl` may have buffering issues on Windows, and those may be the culprit of a broken virtual terminal support. Or maybe it is something else that causes a similar defect.

**Comment by hrumhurum** [comment] 2023-08-19 18:34
Update: the problem turned out to be in the console encoding. Previously, the OS I worked at was configured to use English (United States) encoding for non-Unicode programs and it caused problems in `flyctl ssh console`.

However, since Windows 11 it is now possible to use UTF-8 by default. The enclosed screenshots show how to activate the UTF-8 option in Windows 11:

1. Settings -> Time & Language -> Administrative language settings:

![Window_1](https://github.com/superfly/flyctl/assets/1406964/1fda7ccb-08fe-415a-ac0a-955c75f7600f)

2. Administrative -> Change system locale...

![Window_2](https://github.com/superfly/flyctl/assets/1406964/fbf8ef04-ff8b-4645-a078-8e8f44c005e5)

3. Check "Use Unicode UTF-8 for worldwide language support" option.

## Proposed Solution

The right fix for this situation is to programmatically set the console encoding to UTF-8 at the very start of `flyctl` app using [`SetConsoleCP`](https://learn.microsoft.com/en-us/windows/console/setconsolecp) Windows API function. The value of `wCodePageID` parameter for UTF-8 encoding is `65001`. In this way, `flyctl` will do the right job regardless of the system setting. This will also cover those Windows users who cannot set UTF-8 encoding for non-Unicode programs at the system level due to an older Windows version, or due to compatibility issues with other apps.

**Comment by ndarilek** [comment] 2023-08-21 15:48
Awesome, thanks for this in-depth analysis!

Console encodings aren't my jam but I tried implementing this. I tried calling the function in question [here](https://github.com/superfly/flyctl/blob/5ac0dcb473c80b31ef99824392fc04b377219824/main_windows.go#L6) but got the following crash:

```
panic: runtime error: invalid memory address or nil pointer dereference                                                 
[signal 0xc0000005 code=0x0 addr=0x0 pc=0x1e93c3b]                                                                      
                                                                                                                        
goroutine 1 [running]:                                                                                                  
main.init.0()                                                                                                           
        C:/Users/nolan/projects/flyctl/main_windows.go:6 +0x1b                                                          
exit status 2                                                                                                           
```

Not sure if this is a case of me needing to explicitly link a DLL, using an older library when there's a better choice, failing to do some other relevant console initialization, or... Putting this out there in case anyone has any pointers.

Thanks again.

**Comment by hrumhurum** [comment] 2023-08-21 18:19
`SetConsoleCP` is a very simple Windows API function that should never crash unless there is a problem on the caller's side. I think that the Windows API wrapper library you use (https://github.com/tHinqa/outside-windows) may have a bug.

Here is C++ code that works and shows the concept:

```c++
#include <iostream>
#include <windows.h>

using namespace std;

int main()
{
    if (!SetConsoleCP(CP_UTF8)) // the value of CP_UTF8 is 65001
        cerr << "Cannot set the console input code page." << endl;
    if (!SetConsoleOutputCP(CP_UTF8))
        cerr << "Cannot set the console output code page." << endl;
    
    cout << "Hello, Unicode world!" << endl;
    cout << "© Contoso™ by Microsoft®" << endl; // print some UTF-8 symbols for test
}
```

It runs successfully and prints the Unicode symbols correctly.

**Comment by alichay** [comment] 2023-08-22 16:39
> I think that the Windows API wrapper library you use (https://github.com/tHinqa/outside-windows) may have a bug

I suspect it has an initializer you have to call to load the function pointers. Regardless, that PR above should fix this problem (fingers crossed!)

**Comment by ndarilek** [comment] 2023-08-24 15:26
Good call. There is indeed an initializer, but unfortunately adding it gives me:

```
# github.com/tHinqa/outside-windows/commctrl                                                                            
..\..\go\pkg\mod\github.com\t!hinqa\outside-windows@v0.0.0-20131225231147-79e174abeec9\commctrl\commctrl.go:46:21: syntax error: mixed named and unnamed parameters                                                                             
# github.com/tHinqa/outside-windows/mmsystem                                                                            
..\..\go\pkg\mod\github.com\t!hinqa\outside-windows@v0.0.0-20131225231147-79e174abeec9\mmsystem\mmsystem.go:360:15: syntax error: mixed named and unnamed parameters                                                                            
# github.com/tHinqa/outside-windows/winuser                                                                             
..\..\go\pkg\mod\github.com\t!hinqa\outside-windows@v0.0.0-20131225231147-79e174abeec9\winuser\winuser.go:208:27: syntax error: mixed named and unnamed parameters                                                                              
# github.com/tHinqa/outside-windows/winbase                                                                             
..\..\go\pkg\mod\github.com\t!hinqa\outside-windows@v0.0.0-20131225231147-79e174abeec9\winbase\winbase.go:1558:6: syntax error: mixed named and unnamed parameters                                                                              
```

Still a bit new to Go, but this particular Windows library hasn't been updated in a decade so I'm wondering if a language change broke it? If anyone has suggestions for a better one then I'm happy to switch this over--I just googled for the function and golang, so maybe there are better Windows bindings that I've missed.

**Closed** 2023-10-20 00:23 UTC
Labels: bug, os:windows
