### ISSUE TITLE
wireguard test command

### ISSUE THREAD

**Issue by michaeldwan** [superfly/flyctl#453] opened 2021-07-14 18:49 UTC
We need a way to debug system and userland wireguard connections. A command like `flyctl wireguard check` would be great. It would also be helpful if the check results were printed after remote builders and `ssh console` tunnels fail. 

A simple approach could be printing the DNS response from `TXT _apps.internal` using `net.DefaultResolver` and again with a new Resolver using the [WireGuard dialer](https://github.com/superfly/flyctl/blob/master/internal/build/imgsrc/docker.go#L204-L222). Bonus points for a flag to provide a DNS entry and type.

**Comment by rugwirobaker** [comment] 2021-07-16 12:30
What do you think of this?:
```sh
./bin/flyctl wireguard check 
Checking for WireGuard bridge status...
+----------------+------+-------+------+----------------------------------+------------+
|      NAME      | TYPE | CLASS | TLL  |             ADDRESS              | NAMESERVER |
+----------------+------+-------+------+----------------------------------+------------+
| _apps.internal | TXT  | IN    | 300s | [flyscale,codechef,flying-whale] | 8.8.8.8    |
+----------------+------+-------+------+----------------------------------+------------+
```

**Comment by michaeldwan** [comment] 2021-07-16 15:41
That's great. I'm not sure how we'll use this yet so let's get something working and we can tweak format later. 

I'd like to guide people to this check after ssh and remote builder connections fail, maybe even run it automatically. I've been thinking of it somewhat like a pass/fail unit test summary. The User-Mode connection might succeed and show a green checkmark with output like you have above while the system wg fails because it isn't setup. Then after printing the status and results of each check, print a success/fail message with a success/fail exit code.

**Comment by tqbf** [comment] 2021-07-16 16:01
One thing I'd very much like for this to do is to ping the DNS server, with ICMP6, as well as looking up requests. Ping is a more direct test of connectivity.

Another thing it should do is verify that the tunnel's DNS server starts with `fdaa`, because there's a very weird bug in here where sometimes people are getting their host's DNS server, not the tunnel's.

**Comment by michaeldwan** [comment] 2021-07-16 16:09
That's a great idea.

**Comment by rugwirobaker** [comment] 2021-07-16 19:03
> . I've been thinking of it somewhat like a pass/fail unit test summary. The User-Mode connection might succeed and show a green checkmark with output like you have above while the system wg fails because it isn't setup. Then after printing the status and results of each check, print a success/fail message with a success/fail exit code.

I like this idea because later on, it may become an event that more validation tests are needed and it would be like adding another element to an array of tests.

**Comment by rugwirobaker** [comment] 2021-07-16 19:05
> Another thing it should do is verify that the tunnel's DNS server starts with `fdaa`, because there's a very weird bug in here where sometimes people are getting their host's DNS server, not the tunnel's.

I thought this was a feature  😄. But then given It happens only half the time.

**Comment by tqbf** [comment] 2021-07-16 23:17
Ok let me just say real quick that if you can figure out why we occasionally get the wrong DNS server on these tunnels, or even just a set of steps that reliably causes the bug to happen, you'd be doing us a HUGE favor.

**Comment by rugwirobaker** [comment] 2022-01-27 20:30
@azazeal yep

**Comment by azazeal** [comment] 2022-01-28 11:15
Duplicate of #675

**Closed by azazeal** 2022-01-28 11:15 UTC
Labels: enhancement
