### ISSUE TITLE
fly deploy hangs ~5-10% of the time with v0.1.52

### ISSUE THREAD

**Issue by tvdfly** [superfly/flyctl#2542] opened 2023-07-08 09:08 UTC
`fly deploy` hangs ~5-10% of the time for me after updating to v0.1.52.

`fly deploy` gets to here and stalled for a few minutes:
```
--> Pushing image done
image: registry.fly.io/my-app:deployment-01CAFECAFECAFECAFECAFECAFE
image size: 241 MB

Watch your app at https://fly.io/apps/my-app/monitoring

Running my-app release_command: /opt/app/bin/migrate
  release_command 90red completed successfully
Updating existing machines in 'my-app' with rolling strategy
  Machine 17red [app] has state: started
  [1/1] Checking that 17red [app] is up and running
```

the machine is running and logs show it working. then i ran `kill -s SIGUSR2 39459` (these are just the stacks that had flyctl paths):
```
1 @ 0x102517ee4 0x1024e5ebc 0x1024e5a24 0x102d2210c 0x102d21f18 0x1025487d4
#       0x102d2210b     github.com/superfly/flyctl/internal/task.(*manager).RunFinalizer.func1+0x3b     /home/runner/work/flyctl/flyctl/internal/task/task.go:100
#       0x102d21f17     github.com/superfly/flyctl/internal/task.(*manager).Start.func1.1+0x67          /home/runner/work/flyctl/flyctl/internal/task/task.go:84

1 @ 0x102517ee4 0x1024e5ebc 0x1024e5a44 0x102d21da4 0x1025487d4
#       0x102d21da3     github.com/superfly/flyctl/internal/task.(*manager).Start.func1+0xa3    /home/runner/work/flyctl/flyctl/internal/task/task.go:80

1 @ 0x102517ee4 0x10252969c 0x102529679 0x102543ec8 0x102552e88 0x102987c60 0x102987bed 0x1029876f4 0x102977c84 0x102977078 0x102976f7d 0x102976e40 0x10297afa4 0x1029ed0cc 0x1035b7044 0x102514f24 0x1024f272c 0x102974ce0 0x102987ae0 0x102977c84 0x102976d08 0x102976d09 0x10297ae4c 0x1029ecb7c 0x1029ecb69 0x10297abc0 0x1029ecab0 0x1029eca71 0x102f54bc0 0x102f54558 0x102f52098 0x102fc1bd8
#       0x102543ec7     sync.runtime_SemacquireMutex+0x27                                                               /opt/hostedtoolcache/go/1.20.5/x64/src/runtime/sema.go:77
#       0x102552e87     sync.(*Mutex).lockSlow+0x177                                                                    /opt/hostedtoolcache/go/1.20.5/x64/src/sync/mutex.go:171
#       0x102987c5f     sync.(*Mutex).Lock+0x9f                                                                         /opt/hostedtoolcache/go/1.20.5/x64/src/sync/mutex.go:90
#       0x102987bec     github.com/getsentry/sentry-go.(*HTTPSyncTransport).disabled+0x2c                               /home/runner/go/pkg/mod/github.com/getsentry/sentry-go@v0.19.0/transport.go:563
#       0x1029876f3     github.com/getsentry/sentry-go.(*HTTPSyncTransport).SendEvent+0xa3                              /home/runner/go/pkg/mod/github.com/getsentry/sentry-go@v0.19.0/transport.go:515
#       0x102977c83     github.com/getsentry/sentry-go.(*Client).processEvent+0x263                                     /home/runner/go/pkg/mod/github.com/getsentry/sentry-go@v0.19.0/client.go:593
#       0x102977077     github.com/getsentry/sentry-go.(*Client).CaptureEvent+0x1e7                                     /home/runner/go/pkg/mod/github.com/getsentry/sentry-go@v0.19.0/client.go:397
#       0x102976f7c     github.com/getsentry/sentry-go.(*Client).RecoverWithContext+0xec                                /home/runner/go/pkg/mod/github.com/getsentry/sentry-go@v0.19.0/client.go:448
#       0x102976e3f     github.com/getsentry/sentry-go.(*Client).Recover+0x7f                                           /home/runner/go/pkg/mod/github.com/getsentry/sentry-go@v0.19.0/client.go:412
#       0x10297afa3     github.com/getsentry/sentry-go.(*Hub).Recover+0xc3                                              /home/runner/go/pkg/mod/github.com/getsentry/sentry-go@v0.19.0/hub.go:319
#       0x1029ed0cb     github.com/superfly/flyctl/internal/sentry.Recover+0xab                                         /home/runner/work/flyctl/flyctl/internal/sentry/sentry.go:128
#       0x1035b7043     main.run.func1+0x33                                                                             /home/runner/work/flyctl/flyctl/main.go:40
#       0x102514f23     runtime.gopanic+0x203                                                                           /opt/hostedtoolcache/go/1.20.5/x64/src/runtime/panic.go:884
#       0x1024f272b     runtime.mapassign_faststr+0x3db                                                                 /opt/hostedtoolcache/go/1.20.5/x64/src/runtime/map_faststr.go:205
#       0x102974cdf     github.com/getsentry/sentry-go/internal/ratelimit.Map.Merge+0xcf                                /home/runner/go/pkg/mod/github.com/getsentry/sentry-go@v0.19.0/internal/ratelimit/map.go:43
#       0x102987adf     github.com/getsentry/sentry-go.(*HTTPSyncTransport).SendEvent+0x48f                             /home/runner/go/pkg/mod/github.com/getsentry/sentry-go@v0.19.0/transport.go:548
#       0x102977c83     github.com/getsentry/sentry-go.(*Client).processEvent+0x263                                     /home/runner/go/pkg/mod/github.com/getsentry/sentry-go@v0.19.0/client.go:593
#       0x102976d07     github.com/getsentry/sentry-go.(*Client).CaptureEvent+0x57                                      /home/runner/go/pkg/mod/github.com/getsentry/sentry-go@v0.19.0/client.go:397
#       0x102976d08     github.com/getsentry/sentry-go.(*Client).CaptureException+0x58                                  /home/runner/go/pkg/mod/github.com/getsentry/sentry-go@v0.19.0/client.go:388
#       0x10297ae4b     github.com/getsentry/sentry-go.(*Hub).CaptureException+0xab                                     /home/runner/go/pkg/mod/github.com/getsentry/sentry-go@v0.19.0/hub.go:260
#       0x1029ecb7b     github.com/getsentry/sentry-go.CaptureException+0x8b                                            /home/runner/go/pkg/mod/github.com/getsentry/sentry-go@v0.19.0/sentry.go:54
#       0x1029ecb68     github.com/superfly/flyctl/internal/sentry.CaptureException.func1+0x78                          /home/runner/work/flyctl/flyctl/internal/sentry/sentry.go:81
#       0x10297abbf     github.com/getsentry/sentry-go.(*Hub).WithScope+0x5f                                            /home/runner/go/pkg/mod/github.com/getsentry/sentry-go@v0.19.0/hub.go:200
#       0x1029ecaaf     github.com/getsentry/sentry-go.WithScope+0xcf                                                   /home/runner/go/pkg/mod/github.com/getsentry/sentry-go@v0.19.0/sentry.go:95
#       0x1029eca70     github.com/superfly/flyctl/internal/sentry.CaptureException+0x90                                /home/runner/work/flyctl/flyctl/internal/sentry/sentry.go:76
#       0x102f54bbf     github.com/superfly/flyctl/flaps.sendFlapsCallMetric+0x1ef                                      /home/runner/work/flyctl/flyctl/flaps/flaps.go:616
#       0x102f54557     github.com/superfly/flyctl/flaps.(*Client).sendRequest+0x2e7                                    /home/runner/work/flyctl/flyctl/flaps/flaps.go:596
#       0x102f52097     github.com/superfly/flyctl/flaps.(*Client).Get+0xd7                                             /home/runner/work/flyctl/flyctl/flaps/flaps.go:325
#       0x102fc1bd7     github.com/superfly/flyctl/internal/machine.(*leasableMachine).WaitForSmokeChecksToPass+0x177   /home/runner/work/flyctl/flyctl/internal/machine/leasable_machine.go:254
```

flyctl didn't respond to ctrl+c. Sending HUP ended up stopping it.

versions:
```
uname -a
Darwin tvd-m1-pro.local 22.5.0 Darwin Kernel Version 22.5.0: Thu Jun  8 22:22:20 PDT 2023; root:xnu-8796.121.3~7/RELEASE_ARM64_T6000 arm64
fly version
fly v0.1.52 darwin/arm64 Commit: 9928dce858ee7d597f7af9068fca6e72893f3c56 BuildDate: 2023-07-07T23:18:26Z
```

**Comment by MikeyJL** [comment] 2023-07-09 10:32
I'm getting the same issue on my end, and it's hanging most if not most of the time when I deploy. I've first encountered this hanging issue about 5 days ago and I'm using it in a GitHub Action.

Also, I've tried different deployment strategies where ```rolling``` and ```canary``` will hang for me at the below (omitted IDs).

```
Updating existing machines in '******' with rolling strategy
  [1/2] Updating ***** [app]
  [1/2] Waiting for ***** [app] to have state: started
  Machine ***** [app] has state: started
  [1/2] Checking that ***** [app] is up and running
```

However, when I tried ```bluegreen```, I'm getting the below error, not sure if it's related. If not, let me know if I should create a new issue for it.

```
panic: assignment to entry in nil map

goroutine 1108 [running]:
github.com/getsentry/sentry-go/internal/ratelimit.Map.Merge(0xc000304900?, 0xc000ce4100?)
	/home/runner/go/pkg/mod/github.com/getsentry/sentry-go@v0.19.0/internal/ratelimit/map.go:43 +0x108
github.com/getsentry/sentry-go.(*HTTPSyncTransport).SendEvent(0xc00011d100, 0xc000e06500)
	/home/runner/go/pkg/mod/github.com/getsentry/sentry-go@v0.19.0/transport.go:548 +0x525
github.com/getsentry/sentry-go.(*Client).processEvent(0xc0000b0300, 0xc000e06500, 0xc000d845a0, {0x1dbede0, 0xc000ee3440})
	/home/runner/go/pkg/mod/github.com/getsentry/sentry-go@v0.19.0/client.go:593 +0x2cc
github.com/getsentry/sentry-go.(*Client).CaptureEvent(...)
	/home/runner/go/pkg/mod/github.com/getsentry/sentry-go@v0.19.0/client.go:397
github.com/getsentry/sentry-go.(*Client).CaptureException(0xc00087f9b0?, {0x1dbe7a0?, 0xc000ecbd00?}, 0xc000ecbd00?, {0x1dbede0, 0xc000ee3440})
	/home/runner/go/pkg/mod/github.com/getsentry/sentry-go@v0.19.0/client.go:388 +0x65
github.com/getsentry/sentry-go.(*Hub).CaptureException(0xc0003044b0, {0x1dbe7a0?, 0xc000ecbd00})
	/home/runner/go/pkg/mod/github.com/getsentry/sentry-go@v0.19.0/hub.go:260 +0xbe
github.com/getsentry/sentry-go.CaptureException(...)
	/home/runner/go/pkg/mod/github.com/getsentry/sentry-go@v0.19.0/sentry.go:54
github.com/superfly/flyctl/internal/sentry.CaptureException.func1(0xc0003044b0?)
	/home/runner/work/flyctl/flyctl/internal/sentry/sentry.go:81 +0x89
github.com/getsentry/sentry-go.(*Hub).WithScope(0xc0003044b0, 0xc00087fa80)
	/home/runner/go/pkg/mod/github.com/getsentry/sentry-go@v0.19.0/hub.go:200 +0x6d
github.com/getsentry/sentry-go.WithScope(...)
	/home/runner/go/pkg/mod/github.com/getsentry/sentry-go@v0.19.0/sentry.go:95
github.com/superfly/flyctl/internal/sentry.CaptureException({0x1dbe7a0?, 0xc000ecbd00?}, {0x0?, 0x2?, 0x2?})
	/home/runner/work/flyctl/flyctl/internal/sentry/sentry.go:76 +0xe5
github.com/superfly/flyctl/flaps.sendFlapsCallMetric({0x1dd2350, 0xc0010c30e0}, {0xc0010b2230, 0xf}, {{0x560ad1?, 0xc000d46168?, 0x2a1cfa0?}, 0x2a4eca0?}, 0xc8)
	/home/runner/work/flyctl/flyctl/flaps/flaps.go:616 +0x252
github.com/superfly/flyctl/flaps.(*Client).sendRequest(0xc000cd9380, {0x1dd2350, 0xc0010c30e0}, {0x19f5737, 0x3}, {0xc0010b2230, 0xf}, {0x0, 0x0}, {0x196e300, ...}, ...)
	/home/runner/work/flyctl/flyctl/flaps/flaps.go:596 +0x432
github.com/superfly/flyctl/flaps.(*Client).Get(0x6fc23ac00?, {0x1dd2350, 0xc0010c30e0}, {0xc000e8d140, 0xe})
	/home/runner/work/flyctl/flyctl/flaps/flaps.go:325 +0x11c
github.com/superfly/flyctl/internal/command/deploy.(*blueGreen).WaitForGreenMachinesToBeHealthy.func1({0x1dddda0, 0xc0009bea00})
	/home/runner/work/flyctl/flyctl/internal/command/deploy/strategy_bluegreen.go:276 +0x106
created by github.com/superfly/flyctl/internal/command/deploy.(*blueGreen).WaitForGreenMachinesToBeHealthy
	/home/runner/work/flyctl/flyctl/internal/command/deploy/strategy_bluegreen.go:267 +0x30a
Error: Process completed with exit code 2.
```

**Comment by smorimoto** [comment] 2023-07-09 13:35
I've seen the same problem with `bluegreen`, but also seems to hang on things like `fly m list`.

**Comment by carrete** [comment] 2023-07-10 12:26
Happens to me 100% of the time. First noticed it deploying Postgres, i.e. `fly postgres`. 0.1.51 works without issue

**Comment by michaeldwan** [comment] 2023-07-10 16:41
Thanks for the info everyone. We're looking into it!

**Comment by MikeyJL** [comment] 2023-07-12 16:50
Not sure if anything has been actioned from your side @michaeldwan

But I'm not getting the error above anymore and it's not hanging. Just now I was able to deploy using ```bluegreen```. I've tested with ```canary``` as well and that seems to be working too.

**Comment by michaeldwan** [comment] 2023-07-12 19:21
@MikeyJL We reverted a change that was causing the issue, but we're not sure why it was happening in the first place since we can't reproduce it. We have theories that we're testing out now, and we'll close this issue once we're certain the problem is solved.

**Comment by kzys** [comment] 2023-07-17 18:43
We've reverted the change in v0.1.53.

https://github.com/superfly/flyctl/releases/tag/v0.1.53

**Closed by kzys** 2023-07-17 18:43 UTC
Labels: bug
