### ISSUE TITLE
Modifying machine volume mount 'succeeds' without making change

### ISSUE THREAD

**Issue by OJFord** [superfly/flyctl#1758] opened 2023-02-22 15:09 UTC
*Please only report specific issues with `flyctl` behavior*. Anything like a support request for your application should go to https://community.fly.io. More people watch that space and can help you faster!

**Describe the bug**
Briefly, describe what broke and provide the following details:

With a machine  currently running with some volume `vol_a` mounted at `/data`:

```
$flyctl -a app123 machine update machine123 --volume=vol_b:/data
```

should modify the mount to be now `vol_b` at the same location.

> ? Apply changes? Yes
> Updating machine machine123
> No health checks found
> Machine machine123 updated successfully! 

Sounds good. `$flyctl -a app123 machine status machine123`:
```
[...]
Volume = vol_a
[...]
```

Since there's also apparently no way to just detach a volume, (`--volume=:/data` errors 'not enough unattached volumes for ''') and `--volume=[]` errors 'cannot infer volume and mount path from '[]') I'm unsure how to proceed.

* Operating system Linux
* `fly version` flyctl v0.0.464 linux/amd64 Commit: f9840dd8 BuildDate: 2023-02-22T09:52:30Z

** Paste your `fly.toml`
N/A

** Command output: **

**Comment by tvdfly** [comment] 2023-02-22 16:45
looks like a duplicate of https://github.com/superfly/flyctl/issues/1605

we're probably going to remove that flag from `fly machine update`, since our machines don't currently support moving between hosts, which is likely required (unless the volumes happen to be created on the same physical server). 

The best option is to a machine with the same config and associate that new machine with vol_b. `fly m clone`  with `--attach-volume` can do that.

**Closed** 2023-02-22 16:52 UTC
Labels: bug
