### ISSUE TITLE
can’t use command ’ flyctl ssh issue –agent’ in windows

### ISSUE THREAD

**Issue by lyj0309** [superfly/flyctl#949] opened 2022-04-27 15:03 UTC
when i want to issue a new ssh key, the flyctl goes worng like this in windows.
![image](https://user-images.githubusercontent.com/50474995/165548826-3e7392b3-a376-4420-b48c-b36ba899304a.png)

**Comment by lyj0309** [comment] 2022-04-27 15:05
for more details see in <https://community.fly.io/t/cant-use-command-flyctl-ssh-issue-agent/4903/5>

**Comment by mrkishi** [comment] 2022-04-27 23:21
Duplicate of #944.

**Comment by jsierles** [comment] 2022-04-28 04:01
Oops, indeed a duplicate. Will close here and comment on the other thread.

**Closed by jsierles** 2022-04-28 04:01 UTC
Labels: bug
