### ISSUE TITLE
Flyctl x86 exe release not working

### ISSUE THREAD

**Issue by planyway** [superfly/flyctl#1218] opened 2022-08-28 04:37 UTC
I received “Error loading config While parsing config: yaml: control characters are not allowed
flyctl is a command line interface to the Fly.io platform.” when I run any flyctl command, the way I setup is by unzipping the x86 release zip file, which includes flyctl.exe and wintun.dll. The problem did not occur at the beginning of using flyctl.exe, until a crash of my computer when deploying my site.
My operating system is Windows 64, my flyctl folder is extracted from is 0.0.381_Windows_x86_64.zip

fly.toml is exactly the auto generated one, no edits yet.
No any other setup made for my hello world version app.

**Comment by catflydotio** [comment] 2023-01-25 00:03
Duplicate of #908.

**Closed by catflydotio** 2023-01-25 00:03 UTC
Labels: bug
