### ISSUE TITLE
fly logs is not working

### ISSUE THREAD

**Issue by muddi900** [superfly/flyctl#1407] opened 2022-10-24 19:45 UTC
## Describe the bug
`flyct logs -a <app_name>` results in nothing. The shell remains frozen.

### Operating system
* `fly.exe v0.0.417 windows/amd64 Commit: 3750068b BuildDate: 2022-10-21T22:52:18Z`
* `flyctl v0.0.417 linux/amd64 Commit: 3750068b BuildDate: 2022-10-21T22:52:18Z`

## Paste your `fly.toml`

```toml
app = "tpw-fam-app"
kill_signal = "SIGINT"
kill_timeout = 5

[env]

[experimental]
  allowed_public_ports = []
  auto_rollback = true
  entrypoint = []
  exec = []
  private_network = true

[build]
  dockerfile = "Dockerfile.publish"

[[services]]
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"

  [[services.http_checks]]
    interval = 10000
    grace_period = "5s"
    method = "get"
    path = "/healthcheck"
    protocol = "http"
    restart_limit = 0
    timeout = 2000
    tls_skip_verify = false
```

** Command output: **

Nothing, the shell just freezes until I press CTRL+C

**Comment by muddi900** [comment] 2022-10-25 21:01
Just upgraded the tool on version 0.0.420 and the issue remains on both platform.

**Comment by catflydotio** [comment] 2023-01-24 23:56
This doesn't seem to be a flyctl bug; if it was, it's obsolete. Closing. Feel free to reopen if this isn't the case.

**Closed** 2023-01-24 23:56 UTC
Labels: bug

**Comment by Hirrolot** [comment] 2023-06-24 15:32
I'm catching this bug right now. The bug remains in the version `flyctl v0.1.38`.

**Comment by catflydotio** [comment] 2023-06-24 17:44
Hi @Hirrolot, to be clear, if `fly logs` doesn't give you any output, it's most likely not a bug in the `flyctl` tool. We are investigating further customer reports of missing logs today, however: check out https://status.flyio.net/ for updates.
