### ISSUE TITLE
Fly postgres create without an App name fails

### ISSUE THREAD

**Issue by greg-mckeon** [superfly/flyctl#1390] opened 2022-10-18 20:08 UTC
*Please only report specific issues with `flyctl` behavior*. Anything like a support request for your application should go to https://community.fly.io. More people watch that space and can help you faster!

**Describe the bug**
Briefly, describe what broke and provide the following details:
Running fly postgres create on a brand new account with no App returns "Error Could not find App"

1) Create new account.
2) run fly postgres create
3) leave app blank, to generate a new one.
4) Observe the output below.

* Operating system
* `fly version` fly v0.0.414 darwin/arm64 Commit: 463a8297 BuildDate: 2022-10-17T21:15:34Z

** Paste your `fly.toml`
None.

** Command output: **

```text
? Choose an app name (leave blank to generate one):
automatically selected personal organization: Greg McKeon
? Select regions: Secaucus, NJ (US) (ewr)
? Select configuration: Development - Single node, 1x shared CPU, 256MB RAM, 1GB disk
Creating postgres cluster  in organization personal
Creating app...
Setting secrets...
Error Could not find App
```

**Comment by shortdiv** [comment] 2022-11-25 21:55
Hmm, I tried to reproduce this but I'm not seeing the same results. Are you still having issues with this?

**Comment by catflydotio** [comment] 2023-03-31 20:08
Closing, since not reproduced and quite old.

**Closed by catflydotio** 2023-03-31 20:08 UTC
Labels: bug
