### ISSUE TITLE
Cannot deploy an app using flyctl in a container.

### ISSUE THREAD

**Issue by carrete** [superfly/flyctl#2305] opened 2023-05-18 19:49 UTC
I have a script that uses podman to run flyctl in a container.

```bash
#!/usr/bin/env bash
# -*- coding: utf-8; mode: sh -*-
set -euo pipefail
IFS=$'\n\t'

podman run --rm -it --pull always -q                                            \
    --volume "$PWD:/mnt/workdir"                                                \
    --workdir /mnt/workdir                                                      \
    docker.io/flyio/flyctl:v0.1.8                                               \
    -t "$FLY_ACCESS_TOKEN"                                                      \
    "$@"
```

This is run like `flyctl deploy -i ghcr.io/carrete/hello-world-container:e8fd38059195acf55a720c258a17b8fdf254c3f0`, and produces the error below. 

`FLY_ACCESS_TOKEN` is set and correct when run. The app can be created with this script, for example `flyctl apps create hello-world-container`.

However, the native macOS version of flyctl installed via brew does work which is run like `flyctl -t $FLY_ACCESS_TOKEN deploy -i ghcr.io/carrete/hello-world-container:e8fd38059195acf55a720c258a17b8fdf254c3f0`. 

Please note, `~/.fly` is removed each time before the native macOS version of flyctl is run.

* Operating system (`uname -a`)
> Darwin Patagonica 22.4.0 Darwin Kernel Version 22.4.0: Mon Mar  6 21:00:17 PST 2023; root:xnu-8796.101.5~3/RELEASE_X86_64 x86_64 i386 Darwin

* `fly version`
> flyctl v0.1.8 linux/amd64 Commit: 8c7a3494a027b7ebfe503a516d0080c5ef8080e1 BuildDate: 2023-05-18T17:26:53Z

Versions 0.1.4-7 also do not work, and produce the same error.

* `podman --version`
> podman version 4.5.0

Latest version of docker desktop also does not work.

** Paste your `fly.toml`

```toml
app = "hello-world-container"
primary_region = "scl"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
```

** Command output: **

```text
==> Verifying app config
Validating /mnt/workdir/fly.toml
Platform: machines
✓ Configuration is valid
--> Verified app config
==> Building image
Searching for image 'ghcr.io/carrete/hello-world-container:e8fd38059195acf55a720c258a17b8fdf254c3f0' remotely...
image found: img_8y6w4zylmd2v7rn3

Watch your app at https://fly.io/apps/hello-world-container/monitoring

Error: failed to list VMs: invalid authentication
```

**Comment by pborzenkov** [comment] 2023-05-19 14:17
@carrete Should be fixed by https://github.com/superfly/flyctl/pull/2309

**Comment by carrete** [comment] 2023-05-22 19:22
Thanks @pborzenkov. This is now working for me with 0.1.9.

**Closed** 2023-05-22 19:22 UTC
Labels: bug

**Comment by pborzenkov** [comment] 2023-05-23 07:50
@carrete We had to revert that PR because it introduced a regression (0.1.10 no longer contains the change). I'll make another attempt today.
