### ISSUE TITLE
Support for custom (public) docker registries

### ISSUE THREAD

**Issue by pinkiebell** [superfly/flyctl#75] opened 2020-03-08 20:07 UTC
Adding support for other public docker registries would be super nice.
Trying to deploy images from `docker.pkg.github.com/...` currently returns `Error Unable to access image docker.pkg.github.com/<PACKAGE:TAG>: 401 Unauthorized`.

I guess the reason is that fly's API tries to fetch from docker hub?

Related #58

**Comment by michaeldwan** [comment] 2020-03-08 20:18
Correct we’re only using docker hub or our registry. We’ll add support for other registries soon!

**Comment by pinkiebell** [comment] 2020-10-01 18:15
Gentle ping. Since the `docker.pkg.github.com` requires authentication for public images, the new github container registry does not. Any plans on supporting the `ghcr.io` on fly.io?

I tried do deploy a test application via a public ghcr image but it hangs on the 
```
==> Optimizing Image
building fs... ⡿ 
```
step for ever.

PS:
🙌🍾 for this simplistic docker hosting platform. Great Job 👍
Do you guys consider making use of `Container on the Edge' as a marketing twist? 🤣

**Comment by michaeldwan** [comment] 2020-10-01 19:11
@pinkiebell thanks for the kind words 😊

We're going to support private registries but no timeframe yet. Do you mind sharing the image that's hanging?

**Comment by pinkiebell** [comment] 2020-10-01 19:15
> @pinkiebell thanks for the kind words 😊
> 
> We're going to support private registries but no timeframe yet. Do you mind sharing the image that's hanging?

<img width="870" alt="Screenshot 2020-10-01 at 21 14 39" src="https://user-images.githubusercontent.com/40266861/94853121-2f622c80-042b-11eb-9493-1dd68ed9987a.png">

**Comment by michaeldwan** [comment] 2020-10-01 20:02
@pinkiebell Looks like there's a bug in our code. That particular image targets several architectures and we weren't choosing the correct one so it was hanging. We'll get a fix out shortly. Otherwise public images on ghcr.io will work just fine.

**Comment by michaeldwan** [comment] 2020-10-01 22:34
@pinkiebell we just pushed a fix for image resolution -- ghcr.io/nutberry/artifacts/habitat:latest is working for me. Sorry about that!

**Comment by pinkiebell** [comment] 2020-10-01 22:38
> @pinkiebell we just pushed a fix for image resolution -- ghcr.io/nutberry/artifacts/habitat:latest is working for me. Sorry about that!

👌Perfect, works.  Btw, I just stumbled upon another bug:
I can't delete a Organization:

```
~ # flyctl orgs delete test
Error Field 'dnsZones' doesn't exist on type 'Organization'
```

Just to let you know 🙂 Thanks 💪

**Comment by michaeldwan** [comment] 2020-10-02 02:55
@pinkiebell thanks for point that out, we'll get it fixed up!

**Comment by pinkiebell** [comment] 2020-10-05 21:46
@michaeldwan 
👋 Hello again.

ghcr.io is broke again with 401 - Authorization required. 🤦‍♂️
Github seems to be more strict now regarding the http requests to ghcr.io.

Best by example:

doesn't work:
```
~ $ curl https://ghcr.io/v2/nutberry/artifacts/habitat/manifests/latest 
{"errors":[{"code":"UNAUTHORIZED","message":"authentication required"}]}
```

works:
```
~ $ curl -H 'Authorization: Bearer' https://ghcr.io/v2/nutberry/artifacts/habitat/manifests/latest
{
   "mediaType": "application/vnd.docker.distribution.manifest.list.v2+json",
   "schemaVersion": 2,
   "manifests": [
      {
         "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
         "digest": "sha256:ac90a5863bd29280fb9d421d91868bd530a0d332562c75d2925e6da71f8e02ff",
         "size": 1575,
         "platform": {
            "architecture": "amd64",
            "os": "linux"
         }
      },
      {
         "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
         "digest": "sha256:fbc80d89b788051c8b531a0737b87c92f270719872115c92d2a717e14906851a",
         "size": 1575,
         "platform": {
            "architecture": "arm64",
            "os": "linux"
         }
      },
      {
         "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
         "digest": "sha256:fa0f12b16007b9835ad7d2e9c37083ef3862c8ca4217514a48e5c654e620ecdb",
         "size": 1575,
         "platform": {
            "architecture": "arm",
            "os": "linux",
            "variant": "v7"
         }
      },
      {
         "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
         "digest": "sha256:8dbc6042b7437944d70f0821149cd2ad2d1247cbf660ce286ec2d752b6340c6f",
         "size": 1575,
         "platform": {
            "architecture": "arm",
            "os": "linux",
            "variant": "v6"
         }
      }
   ]
}                                                                                                                                                            
```

**Comment by michaeldwan** [comment] 2020-10-05 22:39
@pinkiebell I was able to reproduce the issue. There might be an issue obtaining an anonymous token on the realm when the first request fails. We'll dig in and follow up once it's fixed. Sorry about all this :/

**Comment by jsierles** [comment] 2022-02-08 09:56
Closing this issue in favor of a new one specific to adding authenticated registry support.

**Closed by jsierles** 2022-02-08 09:56 UTC
