### ISSUE TITLE
fly ssh console hangs when VM goes away

### ISSUE THREAD

**Issue by mrkurt** [superfly/flyctl#455] opened 2021-07-14 22:50 UTC
When I'm connected to a VM with fly ssh console and then the VM vanishes, `flyctl` hangs it's not easily killable.

I think you can replicate this just by:

1. `fly ssh console` in one terminal
2. `fly vm stop <id-of-what-you're-connected-to>` in another
3. terminal one is now frozen

**Comment by rugwirobaker** [comment] 2021-08-19 15:24
@mrkurt I'm testing this on the #496. The  `fly ssh console` does not freeze, and `exit` exists with `0`

**Comment by mrkurt** [comment] 2021-08-19 16:34
This is still happening for me, specifically when I'm SSH'ed and running a Ruby shell. I think @tqbf might have had a guess about what's up.

**Comment by amalkh5** [comment] 2021-08-19 16:38
@mrkurt @rugwirobaker is still happening to me also.

There workaround for it which is configuring `ServerAliveInterval` values on the `~/.ssh/config`

**Comment by jsierles** [comment] 2022-02-08 10:37
Duplicate of #636

**Closed by jsierles** 2022-02-08 10:37 UTC
Labels: bug
